title: 极客
description: "用于技术交流"
baseurl: "/blogs.github.io"
url: "https://fightingforme.github.io"
root: /blogs.github.io/
theme: 

#导航栏链接
navigation: 
  - title: 首页
    url: /
  - title: 归档
    url: /blog.md
